<?php

namespace CaroGFaimBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends EntityRepository
{
    /**
     * Finds all "category" and order them by "libelle"
     *
     * @return array The entities.
     */
    public function findAll()
    {
        return $this->findBy(array(), array("libelle"=>"ASC"));
    }

    /**
     * Finds all categories with ingredients
     */
    public function findAllCategoriesWithIngredients()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            "SELECT cat, ings
             FROM CaroGFaimBundle:categorie cat
             LEFT JOIN cat.ingredients ings
             ORDER BY cat.libelle ASC"
        );
        $results = $query->getResult();
        return $results;
    }
}
