<?php

namespace CaroGFaimBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * dinerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dinerRepository extends EntityRepository
{
    /**
     * Finds all "diner" and order them by "date"
     *
     * @return array The entities.
     */
    public function findAll()
    {
        return $this->findBy(array(), array("dateDiner"=>"DESC"));
    }
}
