<?php

namespace CaroGFaimBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ingredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ingredientRepository extends EntityRepository
{
}
