<?php

namespace CaroGFaimBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * personneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personneRepository extends EntityRepository
{
    /**
     * Finds all "personne" and order them by "nom", "prenom"
     *
     * @return array The entities.
     */
    public function findAll()
    {
        return $this->findBy(array(), array("nom"=>"ASC", "prenom"=>"ASC"));
    }

}
