<?php

namespace CaroGFaimBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * platRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class platRepository extends EntityRepository
{
    /**
     * Finds all "plat" and order them by "libelle"
     *
     * @return array The entities.
     */
    public function findAll()
    {
        return $this->findBy(array(), array("libelle"=>"ASC"));
    }

}
