<?php

namespace CaroGFaimBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * type_platRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_platRepository extends EntityRepository
{
    /**
     * Finds all entities in the repository.
     *
     * @return array The entities.
     */
    public function findAll()
    {
        return $this->findBy(array(), array("id"=>"asc"));
    }

}
